spring.datasource.url=jdbc:postgresql://db.jdynjezcjrpqlmtnjyzo.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=evqs0fwcU2gzqDuA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null